#!/bin/sh


_recipe_qemu_help() {
    ${PAGER:-cat} <<'EOF'
qemu-img create <file.img> <size>[M|G]
qemu-system-<arch> <args...>
    arch: x86_64
    args: use the other qemu recipes
EOF
}
recipe_add _recipe_qemu_help qemu,HELP


_recipe_qemu_cpu() {
    echo -smp "${1:-1}"
}
recipe_add _recipe_qemu_cpu qemu,cpu


_recipe_qemu_virtual_flash_drive() {
    echo \
        -device piix3-usb-uhci \
        -drive id=pendrive,file="${1:?flash drive img}",format=raw,if=none \
        -device usb-storage,drive=pendrive \
        -boot menu=on
}
recipe_add _recipe_qemu_virtual_flash_drive qemu,virtual_flash_drive


_recipe_qemu_mem() {
    echo -m "${1:-1G}"
}
recipe_add _recipe_qemu_mem qemu,mem


_recipe_qemu_disk() {
    echo -hda "${1:?disk img}"
}
recipe_add _recipe_qemu_disk qemu,disk

_recipe_qemu_cdrom() {
    echo -cdrom "${1:?CD ROM iso}"
}
recipe_add _recipe_qemu_cdrom qemu,cdrom

# vim: ft=sh
