#!/bin/sh


USAGE="$(cat <<EOF
Preview generated commands:
  cat <timestamp_file> | ffmpeg_split -i <to_be_split.mp4>

Execute generated commands:
  cat <timestamp_file> | ffmpeg_split -i <to_be_split.mp4> | sh


The timestamp_file must contain single-column rows with each row being start
timestamp of each chapter. Empty lines will be ignored.

Standard tools like cut, awk, etc. can be used to prepare a timestamp_file
EOF
)"
while getopts 'hi:' opt; do case "$opt" in
    i)    INPUT="$OPTARG" ;;
    h|*)  echo "$USAGE" >&2; exit 1 ;;
esac done
shift $((OPTIND-1))

: "${INPUT:?}"


DURATION="$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$INPUT")" ||
    { 2>&1 echo "Cannot get duration"; exit 1; }

grep . |
awk '
    {
        starts[NR] = $0
    }
    END {
        starts[NR+1] = "'"$DURATION"'"
        for (i=1; i<=NR; i++) {
            printf("%03d %s %s\n", i, starts[i], starts[i+1])
        }
    }
' | 
while read -r index start end; do
    base="$(basename "$INPUT")"
    dir="$(dirname "$INPUT")"
    base_root="${base%.*}"
    base_ext="${base##*.}"
    cat <<CMDS
ffmpeg -nostdin -hide_banner -i "$INPUT" -acodec copy -ss "$start" -to "$end" "${dir}/${base_root}.part_${index}.${base_ext}"
CMDS
done
